### ISSUE TITLE
Investigate DM24 failures

### ISSUE THREAD

**Issue by mmschaefer** [battjt/j1939-84#218] opened 2020-11-09 16:22 UTC
Per client feedback, DM24 are missing retries for DM24 in Part 1 Step 4.  Logic is also being questioned.  We need to validate and verify behaviors on all levels of the requirements.

**Comment by gumbelmj** [comment] 2020-12-24 14:57
Duplicate of #50

**Closed by gumbelmj** 2020-12-24 14:57 UTC
Labels: duplicate
